### PR TITLE
[kumano] Add Xperia 1 and 5 to fixup-mountpoints

### PR DESCRIPTION
**Pull request by Thaodan**
[griffin] Add Xperia 1 fixup-mountpoints

### CODE REVIEW

**Comment by Thaodan** [comment]
On a device running android. The partition layout is always the same.

**Comment by iamsaalim** [comment]
OnePlus pull have a different layout table

**Comment by Thaodan** [comment]
Rebased and added Xperia 5 alias bahamut

**Comment by sledges** [comment]
You might need something like this too: https://github.com/mer-hybris/hybris-boot/pull/193/commits/37f5463ca33e0d4bed838932afbda65c866acda8

To match the rest of commit formatting in this repo: please rename your commit's first line to the way I just renamed this PR (don't forget to add the "to", and no commit description needed in this case).

**Review by mlehtima — APPROVED** [review]

**Pull request merged**
