### PR TITLE
Working hybris-hal for Android M

### PR DESCRIPTION
**Pull request by ghosalmartin**

### CODE REVIEW

**Comment by stskeeps** [comment]
You mean Android M?

**Comment by ghosalmartin** [comment]
Yes Android M

**Comment by sledges** [comment]
Thanks, looks good! Please squash all commits except the one mountpoint one

We have habit to tag commits, so for squashed one you could prepend [marshmallow], and for name mounpoint commit as "[bullhead] Mountpoints for Nexus 5x".

Last but not least, please name commits in present time. I.e. instead of "Removed debug info" name "Remove debug info", so it says what it does (still now:)) and most importantly is easier to read when it gets reverted.

Cheers!

**Comment by ghosalmartin** [comment]
Cleaned up here: https://github.com/mer-hybris/hybris-boot/pull/74

**Pull request closed without merging**
