### PR TITLE
Adds mountpoints for OnePlus 5 (cheeseburger)

### PR DESCRIPTION
**Pull request by xreactx**
[cheesburger] Add mountpoints fixup for OnePlus 5

### CODE REVIEW

**Comment by sledges** [comment]
Please rename this commit as per others in this project e.g. "[cheesburger] Add mountpoints fixup for OnePlus 5"

**Comment by xreactx** [comment]
I tried renaming it... I cannot.

**Comment by sledges** [comment]
You can rename a commit from your command line with `git commit --amend` and then force push.
Ask for help on #sailfishos-porters channel

**Comment by kimmoli** [comment]
(WIP)

**Comment by xreactx** [comment]
edited commit message "[cheeseburger] Add OnePlus 5 to fixup-mountpoints" to match other message format.

**Pull request merged**
