### PR TITLE
[init-script] Check /sys/class/android_usb/android0 to determine which mode is going to be used

### LINKED ISSUE #139: init-script: configfs based usb configuration not working on Nexus 5X (bullhead).
https://github.com/mer-hybris/hybris-boot/commit/ad27186290f5c65dea8c39c913bd739673ef078a will cause Nexus 5X to bootloop because the init script could not initialize USB gadget correctly.

Here is the init.log: https://pastebin.ubuntu.com/p/XXr6frWFn5/
Here is my kernel config: https://github.com/RedL0tus/android_kernel_lge_bullhead/blob/cm-14.1/arch/arm64/configs/lineageos_bullhead_defconfig

Maybe we should prefer using USB gadget mode than configfs for compatibility.

### PR DESCRIPTION
**Pull request by RedL0tus**
Fix #139 (#140)

Change-Id: I1ac21721bc1f018d37f0952a0b968ca0d8c1972e
Signed-off-by: Kay <i@v2bv.net>

### CODE REVIEW

**Comment by krnlyng** [comment]
looks good to me, but i think it would be nicer if the functions where defined before use. that's not an issue in bash, but the file generally has function definitions before use, so maybe we should keep it for readability :).

**Comment by RedL0tus** [comment]
@krnlyng Checkout 0dbba3465cbe6f33d226a52cb4de0022f4099863

**Comment by sledges** [comment]
Thank you, could you squash the two commits into one please?

**Comment by RedL0tus** [comment]
@sledges Done.

**Comment by krnlyng** [comment]
looks good!

**Pull request merged**
